apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /ht/
              port: 8080
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /ht/
              port: 8080
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 15
            periodSeconds: 60
            failureThreshold: 5
          env:
            - name: UWSGI_PROCESSES_AUTO
              value:  "1"
          {{- include "backend_env" . | nindent 12 }}
