apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 500Mi
          image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          command: ["deploy/server/celery_worker.sh"]
          env:
            - name: CELERY_CONCURRENCY
              value: "2"
          {{- include "backend_env" . | nindent 12 }}
