apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: {{ .Values.backend.celery_replicas }} 
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 256Mi
          image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          command: ["docker/server/celery_worker.sh"]
          env:
          {{- include "backend_env" . | nindent 12 }}
