apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      initContainers:
        - name: init-copy
          image:  couchdb:2.3 
          command: ['sh','-c','cp /tmp/*.ini /local.d; ls -lrt /local.d;']
          volumeMounts:
            - name: couchdb-config
              mountPath: /tmp/
            - name: config-storage
              mountPath: /local.d
      containers:
        - name: couchdb
          image: couchdb:3.1.1
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
            - name: config-storage 
              mountPath: /opt/couchdb/etc/local.d 
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-credentials
                  key: user
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-credentials
                  key: password
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-data
        - name: couchdb-config
          configMap:
            name: couchdb-config-files 
        - name: config-storage
          emptyDir: {}
