apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio
      containers:
        - name: minio
          image: minio/minio:13580-51c3fed
          args: [ "server", "--console-address", ":9001", "/data" ]
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
          volumeMounts:
            - name: minio-data
              mountPath: /data
          env:
            - name: CONSOLE_SECURE_TLS_REDIRECT
              value: "false"
            - name: MINIO_ROOT_USER 
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: user 
            - name: MINIO_ROOT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: password 
