{{- define "backend_env" -}}
- name: DOMAIN_NAME
  valueFrom:
    configMapKeyRef:
      name: global-config
      key: domain
- name: DJANGO_DATABASE_NAME
  valueFrom:
    configMapKeyRef:
      name: postgresql-config
      key: name
- name: DJANGO_DATABASE_USER
  valueFrom:
    secretKeyRef:
      name: postgresql-secrets
      key: user
- name: DJANGO_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: postgresql-secrets
      key: password
- name: DJANGO_DATABASE_HOST
  valueFrom:
    configMapKeyRef:
      name: postgresql-config
      key: host
- name: DJANGO_DATABASE_PORT
  valueFrom:
    configMapKeyRef:
      name: postgresql-config
      key: port
- name: DJANGO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: secret_key
- name: DJANGO_ENV
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: env
- name: MINIO_ENDPOINT
  valueFrom:
    configMapKeyRef:
      name: minio-config
      key: endpoint
- name: MINIO_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: minio-secrets
      key: user 
- name: MINIO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: minio-secrets
      key: password 
- name: COUCHDB_USER 
  valueFrom:
    secretKeyRef:
      name: couchdb-secrets
      key: user 
- name: COUCHDB_PASSWORD 
  valueFrom:
    secretKeyRef:
      name: couchdb-secrets
      key: password 
- name: COUCHDB_URL 
  valueFrom:
    configMapKeyRef:
      name: couchdb-config 
      key: url 
- name: DJANGO_SENTRY_DSN
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: sentry
- name: DJANGO_SOCIAL_AUTH_GOOGLE_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_google_key

- name: DJANGO_SOCIAL_AUTH_GOOGLE_SECRET
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_google_secret
- name: DJANGO_DEFAULT_FILE_STORAGE
  value: minio_storage.storage.MinioMediaStorage
{{- end -}}
