apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  domain: {{ if .Values.www_domain }}www.{{ end  }}{{ .Values.domain }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  name: {{ .Values.postgresql.name }} 
  host: {{ .Values.postgresql.host }}
  port: {{ .Values.postgresql.port | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
data:
  url: {{ .Values.couchdb.url }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  env: {{ .Values.backend.env }}
  sentry: {{ .Values.backend.sentry | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config-files
data:
{{ (.Files.Glob "configs/couchdb/*").AsConfig | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  endpoint: {{ .Values.minio.endpoint }}
