apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    {{ if .Values.www_domain }}nginx.ingress.kubernetes.io/from-to-www-redirect: "true"{{ end }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    {{ if .Values.www_domain }}- www.{{ .Values.domain }}{{ end }}
    secretName: tls-hosts
  rules:
  - host: {{ if .Values.www_domain }}www.{{ end  }}{{ .Values.domain }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
      - path: /admin/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path:  /projects/[0-9a-zA-Z]+/export/openapi.(yaml|json)
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /ht/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /graphql/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /static/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080
      - path: /media
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchdb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ if .Values.www_domain }}www.{{ end  }}{{ .Values.domain }} 
    http:
      paths:
      - path: /couchdb(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: couchdb-proxy
            port:
              number: 8080
      - path: /couchdb-admin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: couchdb
            port:
              number: 5984

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
spec:
  rules:
  - host: {{ if .Values.www_domain }}www.{{ end  }}{{ .Values.domain }}
    http:
      paths:
      - path: /minio/
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
      - path: /media
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flower
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  rules:
  - host: {{ if .Values.www_domain }}www.{{ end  }}{{ .Values.domain }} 
    http:
      paths:
      - path: /admin/flower/
        pathType: Prefix
        backend:
          service:
            name: flower
            port:
              number: 5555
