apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage: couchdb_data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-backup
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      storage: couchdb_backup

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      storage: minio
