apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
stringData:
  user: {{ .Values.postgresql.user }}
  password: {{ .Values.postgresql.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
type: Opaque
stringData:
  user: {{ .Values.couchdb.user }}
  password: {{ .Values.couchdb.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  secret_key: {{ .Values.backend.secret_key }}

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
stringData:
  access_key: {{ .Values.minio.access_key }}
  secret_key: {{ .Values.minio.secret_key }}

---

apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.basic_auth.user .Values.basic_auth.password) | b64enc }}
