apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - protocol: TCP
      port: 5984
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: couchdb-proxy
spec:
  selector:
    app: couchdb-proxy
  ports:
    - protocol: TCP
      port: 8080 
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9001
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  selector:
    app: flower
  ports:
    - name: http
      port: 5555
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP

