domain: ""
www_domain: false
frontend:
  image:
    name: ghcr.io/api-projector/frontend 
    # tag: latest 
backend:
  api_replicas: 1
  celery_replicas: 1
  image:
    name: ghcr.io/api-projector/backend
    # tag: latest 
  env: production
  secret_key: ""
  sentry: ""
  social_auth_gitlab_key: ""
  social_auth_gitlab_secret: ""
postgresql:
  user: api_projector
  password: ""
  host: ""
  port: "6432"
  name: ""
couchdb:
  url: "http://couchdb:5984"
  user: "" 
  password: "" 
minio:
  endpoint: "minio:9000"
  access_key: ""
  secret_key: ""
basic_auth:
  user: ""
  password: ""
